spring:
  application:
    name: service-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring_database
    username: tgiwu
    password: Tgiwu@0716
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8810