spring:
  application:
    name: eureka-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: service-config
      profile: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins:  "*"
        allowed-methods: "*"
server:
  port: 8804
