server:
  port: 1100
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    user-service:
      path: /user/**
      serviceId: eureka-client
    feign-service:
      path: /feign/**
      serviceId: service-feign
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMillisecond: 2500
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/